package Pojos.entityMongo;


import com.fasterxml.jackson.annotation.JsonInclude;
import jakarta.persistence.Id;
import lombok.Data;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
@Document(collection = "CashFlowMongoDb")
public class CashFlowMongoDb {

    @Id
    private String id;
    private Integer cashFlowId;
    private String companyCode;
    private String yearEnding;
    private String entityType;
    private Integer months;
    private String type;
    private Double pbt;
    private Double pat;
    private Double depreciation;
    private Double finLease;
    private Double leaseEqRes;
    private Double plInForex;
    private Double gainForex;
    private Double plSaleAsst;
    private Double plSaleInvs;
    private Double pAdjSUndrt;
    private Double interestInc;
    private Double intPaidNet;
    private Double interestNet;
    private Double dividendRecOp;
    private Double dividendNet;
    private Double investments;
    private Double miscIncome;
    private Double amortizationOp;
    private Double assetWOff;
    private Double miscExp;
    private Double paymentToVrs;
    private Double provWOffNt;
    private Double provGraty;
    private Double provDimInv;
    private Double provBdnpa;
    private Double tradeReceivables;
    private Double tradeBillPur;
    private Double inventoryOperation;
    private Double tradePayables;
    private Double taxProvision;
    private Double directTaxes;
    private Double advanceTaxPaid;
    private Double loanAdvance;
    private Double transferReserve;
    private Double otherOperatingAct;
    private Double priorYearAdjust;
    private Double provWriteBack;
    private Double priorYearTax;
    private Double balanceWriteBack;
    private Double otherAssets;
    private Double otherLiabilities;
    private Double changeInDeposit;
    private Double changeInBorrowing;
    private Double discountExpenseLn;
    private Double increaseDecreaseAdvance;
    private Double increaseDecreaseInvs;
    private Double netStockHire;
    private Double lastNetSale;
    private Double excessDepWriteBack;
    private Double premiumLeaseLand;
    private Double extraOrdinaryItem;
    private Double netCashFlowOp;
    private Double purchaseFixedAsset;
    private Double saleFixedAsset;
    private Double capitalWorkInProgress;
    private Double capitalSubsRec;
    private Double purchaseInvestment;
    private Double saleInvestmentInIA;
    private Double acquisitionCompany;
    private Double saleUnderTransExtraItem;
    private Double interestReceived;
    private Double dividendReceivedInIA;
    private Double investmentIncome;
    private Double intraCorpDep;
    private Double investmentInSubs;
    private Double loanToSubs;
    private Double investmentInGroupCo;
    private Double issueSharesAcquiredCompany;
    private Double cancelInvestedCos;
    private Double certifiedDepBank;
    private Double movementLoans;
    private Double otherInvestmentAct;
    private Double movementWorkingCapital;
    private Double amortizationExpIA;
    private Double taxesPaid;
    private Double expensesCapitalized;
    private Double extraOrdinaryItemInIA;
    private Double purchaseFixedAssetLongOrder;
    private Double netIDCurrentAsset;
    private Double netIDAdvance;
    private Double netIDCurrentLiabilities;
    private Double netCashInIA;
    private Double priorIssuedEquityCapital;
    private Double priorIssuedPreferredCapital;
    private Double priorIssuedSharePremium;
    private Double redemptionCapital;
    private Double proceedsIssueDebenture;
    private Double priorBankBorrowing;
    private Double priorLongTermBorrowing;
    private Double priorShortTermBorrowing;
    private Double priorDeposit;
    private Double repaymentBorrowing;
    private Double shareApplication;
    private Double loanCorporateBody;
    private Double dividendPaid;
    private Double interestPaid;
    private Double financeCharges;
    private Double cashCreditAdvance;
    private Double cashCapitalInvestment;
    private Double otherFinancialActivity;
    private Double foreignExchangeGainLossFA;
    private Double sharePremium;
    private Double misExpenseWriteOff;
    private Double saleInvestmentFA;
    private Double reserves;
    private Double currentLiabilities;
    private Double loanDisbursement;
    private Double inventoryFA;
    private Double extraOrdinaryItemFA;
    private Double deferredExpenseBorrowing;
    private Double shareApplicationRefund;
    private Double onRedemptionDebenture;
    private Double offOtherLongTermBorrowing;
    private Double offShortTermBorrowing;
    private Double offFinancialLongLiabilities;
    private Double shelterARes;
    private Double repaidShortTermBorrowing;
    private Double repaidLongTermBorrowing;
    private Double netCashUsedFA;
    private Double foreignExchangeGainLossNetFA;
    private Double netIncreaseDecreaseCash;
    private Double cashStartYear;
    private Double cashEndYear;
    private String modifiedDate;

    // You can add constructors, getters, setters, and other methods as needed
}
