package Pojos.entityMongo;


import com.fasterxml.jackson.annotation.JsonInclude;
import jakarta.persistence.Id;
import lombok.Data;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
@Document(collection = "ConsolidatedCashFlowMongoDb")
public class ConsolidatedCashFlowMongoDb {

    @Id
    private Integer id;
    private Double companyName;
    private Double companyId;
    private String entityType;

    private Double offFinLeaseLiabilities;
    private Double  netIncDecInCashAndEquvlnt;
    private Long companyCode;
    private String yearEnding;
    private Integer months;
    private String type;
    private Double profitsBeforeTax;
    private Double profitsAfterTax;
    private Double depreciation;
    private Double finLeaseAndRentalCharges;
    private Double leaseEqualisation;
    private Double plInForex;
    private Double gainOnForexExchTran;
    private Double plOnSaleOfAssets;
    private Double plOnSaleOfInvestments;
    private Double profitAdjOnSaleOfUndrtkng;
    private Double interestIncome;
    private Double interestPaidNet;
    private Double interestNet;
    private Double dividendReceivedOprtActivity;
    private Double dividendNet;
    private Double investments;
    private Double miscIncome;
    private Double amortisationOfExpensesOprtActivity;
    private Double assetsWrittenOff;
    private Double miscExpenses;
    private Double paymentTowardsVrs;
    private Double provAndWoNet;
    private Double provisionForGratuity;
    private Double provisionForDimunInValueOfInvest;
    private Double provisionsForBadDebtsNpa;
    private Double tradeAndOthReceivables;
    private Double tradeBillSPurchased;
    private Double inventoriesOprtActivity;
    private Double tradePayables;
    private Double taxProvision;
    private Double directTaxesPaid;
    private Double advanceTaxePaid;
    private Double loanAndAdvances;
    private Double transferFromReserve;
    private Double othersFromOprtActivity;
    private Double priorYearAdjusments;
    private Double provisionsWrittenBack;
    private Double priorYearsTaxation;
    private Double balanceWrittenBack;
    private Double otherAssets;
    private Double otherLiabilities;
    private Double changeInDeposits;
    private Double changeInBorrowing;
    private Double discountExpOnLoansWrtOff;
    private Double increaseDecreaseInAdvances;
    private Double increaseDecreaseInInvestments;
    private Double netStockOnHire;
    private Double leasedAssetsNetOfSale;
    private Double excessDepreciationWb;
    private Double premiumOnLeaseOfLand;
    private Double extraOrdinaryItems;
    private Double operationgMinorityInterest;
    private Double operationgShareOfProfitOfAsso;
    private Double netCashFlowOprtngActivity;
    private Double purchaseOfFixedAssets;
    private Double saleOfFixedAssets;
    private Double capitalWip;
    private Double capitalSubsidyRecd;
    private Double investmentInGoodWill;
    private Double purchaseOfInvestments;
    private Double saleOfInvestmentsInvesActivity;
    private Double aquisitionOfCompanies;
    private Double saleOfUndrtkngExtraOrdItem;
    private Double interestReceived;
    private Double devidendReceivedInvesActivity;
    private Double investmentIncome;
    private Double interCorporateDeposits;
    private Double investmentInSubsidiaries;
    private Double loanToSubsidiaries;
    private Double investmentInGroupCos;
    private Double issueOfShOnAcquOfCos;
    private Double cansOfInvestmentInCosAcq;
    private Double certificateOfDepositInBank;
    private Double movementInLoans;
    private Double investingMinorityInterest;
    private Double investingShareOfProfitOfAsso;
    private Double othersFromInvestActivity;
    private Double movementInWorkingCapital;
    private Double amortisationOfExpensesInvesActivity;
    private Double taxesPaid;
    private Double expensesCapitalised;
    private Double extraordinaryItemsInvstActivity;
    private Double purchaseOfFixedAssetsLeasedOut;
    private Double netIncDecInCurrentAsset;
    private Double netIncDecInAdvances;
    private Double netIncDecInCurrentLiab;
    private Double netCashUsedInInvestmentActivity;
    private Double proceedsFromIssueOfEqCapital;
    private Double proceedsFromIssueOfPrefCapital;
    private Double proceedsFromIssueOfSnCapInclShPrem;
    private Double redemptionOfCapital;
    private Double proceedsFromIssueOfDeb;
    private Double proceedsFromBankBorrowings;
    private Double proceedsFromThLTermBorr;
    private Double proceedsFromShTermBorr;
    private Double proceedsFromDeposits;
    private Double repaymentOfBorrowings;
    private Double shareApplication;
    private Double loanFromACorporateBody;
    private Double devidendPaid;
    private Double interestPaid;
    private Double financialCharges;
    private Double cashCreditAdvances;
    private Double cashCapInvestmentSubsidy;
    private Double otherFromFinActivity;
    private Double foreignExchangeGainsLossesFinActivity;
    private Double sharePremium;
    private Double miscExpencesWrittenOff;
    private Double saleOfInvestmentsFinActivity;
    private Double reserves;
    private Double currentLiabilities;
    private Double loanDisbursed;
    private Double inventoriesFinActivitiy;
    private Double extraordinaryItemsFinActivity;
    private Double deferredExpAgainstBorrowing;
    private Double shareApplicationRefund;
    private Double onRedemptionOfDebenture;
    private Double offOtherLongTermBorrowing;
    private Double offShortTermBorrowing;
    private Double shelterAssistanceReserve;
    private Double repaymentOfShortTermBorrow;
    private Double financingShareOfProfitOfAsso;
    private Double proceedsFromSharesIssuedBySubsidiaries;
    private Double proceedsFromIssueOfPerpetualBonds;
    private Double proceedsFromIssueOfSubordinatedDebts;
    private Double repaymentOfLongTermBorrow;
    private Double netCashUsedInFinanceActivity;
    private Double foreignExchangeGainsLossesNetFinActivity;
    private Double netIncDecInCashAndEquvalnt;
    private Double cashAndEquvalntBeginOfYear;
    private Double cashAndEquvalntEndOfYear;
    private String modifiedDate;

}
