package Pojos.entityMongo;

import jakarta.persistence.Id;
import lombok.Data;
import org.springframework.data.mongodb.core.mapping.Document;


@Data

@Document(collection = "PrivateFinancialsInsuranceMongoDb")
public class PrivateFinancialsInsuranceMongoDb {

        @Id
        private Integer id;
        private Integer companyId;
        private String yearEnd;
        private String entityType;
        private String financialType;
        private float conversionFactor;
        private String financialFormat;
        private String updatedOn;
        private String fromDate;
        private String toDate;
        private String reportingStandard;
        private Double premium;
        private Double reinsuranceCeded;
        private Double reinsuranceAccepted;
        private Double premiumsEarnedNet;
        private Double interestDividendsAndRentGross;
        private Double profitOnSaleRedemptionOfInvestments;
        private Double lossOnSaleRedemptionOfInvestments;
        private Double transferGainOnRevaluationInFairValue;
        private Double amortisationOfPremiumOnInvestments;
        private Double othersTech1;
        private Double incomeFromInvestments;
        private Double otherIncome;
        private Double totalIncome;
        private Double claimsIncurred;
        private Double commission;
        private Double operatingExpensesRelatedToInsuranceBusiness;
        private Double depreciation;
        private Double interest;
        private Double netOperatingExpenses;
        private Double premiumDeficiency;
        private Double serviceTaxOnUlc;
        private Double provisionForDoubtfulDebts;
        private Double badDebtsWrittenOff;
        private Double provisionForTax;
        private Double provisionOtherThanTaxation;
        private Double othersTech2;
        private Double benefitsPaidNet;
        private Double interimTerminalBonusesPaid;
        private Double otherExpenses;
        private Double totalExpenses;
        private Double surplusDeficitBeforeTax;
        private Double othersTech3;
        private Double surplusDeficitAfterTax;
        private Double surplusAvailableAtBeginning;
        private Double totalSurplusForAvailable;
        private Double appropriationsBalanceForAppropriations;
        private Double transferToShareholdersAccount;
        private Double fundsForDiscontinuedPolicies;
        private Double fundsForFutureAppropriation;
        private Double othersTech4;
        private Double totalAppropriations;
        private Double amountTransferredFromPolicyholderAccount;
        private Double fireInsurance;
        private Double marineInsurance;
        private Double miscellaneousInsurance;
        private Double operatingProfitTransferredToPolicyholderAccount;
        private Double incomeFromInvestmentsNonTech;
        private Double otherIncomeNonTech;
        private Double totalRevenueTech;
        private Double totalRevenueNonTech;
        private Double expensesOtherThanInsurance;
        private Double depreciationNonTech;
        private Double interestNonTech;
        private Double netOperatingExpensesNonTech;
        private Double badDebtsWrittenOffNonTech;
        private Double provisionsOtherThanTaxNonTech;
        private Double contributionFromShareholderAccount;
        private Double otherExpensesNonTech;
        private Double totalExpensesNonTech;
        private Double pbtTech;
        private Double pbtNonTech;
        private Double provisionForTaxNonTech;
        private Double othersNonTech2;
        private Double patTech;
        private Double patNonTech;
        private Double appropriations;
        private String plBalanceSheetTech;
        private Double plBalanceSheetNonTech;
        private Double earningsPerShare;
        private Double shareCapital;
        private Double shareApplPendingAllot;
        private Double reserveAndSurplus;
        private Double netWorth;
        private Double creditFairValue;
        private Double totalShareholdersFunds;
        private Double borrowings;
        private Double minorityInterest;
        private Double defTaxLiability;
        private Double totalLoansDefTaxLiability;
        private Double policyholdersFunds;
        private Double creditFairValueChangeAcc;
        private Double policyLiabilities;
        private Double insuranceReserves;
        private Double provisionForLinkedLiabilities;
        private Double addFairValueChange;
        private Double fundsForDiscontinuedPoliciesSof;
        private Double totalProvisionForLiabilities;
        private Double totalPolicyholdersFund;
        private Double fundsForFutureAppropriationSof;
        private Double totalLiabilities;
        private Double totalSofFunds;
        private Double shareholders;
        private Double policyholders;
        private Double investments;
        private Double totalInvestments;
        private Double assetsToCoverLinkedLiabilities;
        private Double loan;
        private Double fixedAssets;
        private Double defTaxAssets;
        private Double totalInvestmentsLoansAssets;
        private Double cashBankBalances;
        private Double advancesOtherAssets;
        private Double totalCurrentAssets;
        private Double currentLiabilities;
        private Double provisions;
        private Double deferredTaxLiability;
        private Double totalCurrentLiabilitiesProvisions;
        private Double netCurrentAssets;
        private Double miscExpenditure;
        private Double debitBalanceForPL;
        private Double differenceInRevenue;
        private Double totalAofFunds;
        private Double cashFlowOperations;
        private Double cashFlowInvesting;
        private Double cashFlowFinancing;
        private Double freeCashFlow;
        private Double totalPreferred;
        private Double sharesOutstanding;
        private Double sharesOutstandingFullyDiluted;
        private Double earningsPerShareBasic;
        private Double earningsPerShareDiluted;
        private Double dividend;
        private Double netRetention;
        private Double managementExpenses;
        private Double commissionRatio;
        private Double claimsRatio;
        private Double policyholdersLiabilities;
        private Double growthRate;
        private Double changeInNetworth;
        private Double patMargin;
        private Double surplusToPolicy;
        private Double lossRatio;
        private Double totalFundUnderPA;
        private Double totalFundUnderSA;
        private Double returnOnCapitalEmployed;
        private Double returnOnNetworth;
        private Double operatingProfitMargin;
        private Double pbtMargin;
        private Double reinsuranceAcceptedToGrossPremium;
        private Double reinsuranceCededToGrossPremium;
        private Double incomeFromInvestmentsToGrossPremium;
        private Double netEarningRatio;
        private Double netIncurredClaims;
        private Double combinedRatio;
        private Double investmentYield;
        private Double operatingExpensesRatio;
        private Integer priorityCheck;
        private String pfhDescription;
        private String updatedAt;
        private String createdAt;

        private Double interestTerminalBonusesPaid;


        // Getters and Setters
    }


